### ISSUE TITLE
Changing the default model.

### ISSUE THREAD

**Issue by taesiri** [abhagsain/ai-cli#8]
Hello,

Thank you for your awesome tool. 

Currently, this app uses the [`text-davinci-002`](https://github.com/abhagsain/ai-cli/blob/8537d36478939be8cacc5935cb733de0b1d5f7be/src/commands/ask.ts#L36) model by default. I was wondering if it is possible to add a custom config file/flag so we can change this to other models (e.g., `code-davinci-002`) 

Thanks.

**Comment by abhagsain** [comment]
Sure @taesiri I'll see if someone picks this up otherwise I'll pick it up.

Leaving it here for others and future me.
The ideal UX for this would be
- The users should get the list of available models as a prompt to choose from
   - Not sure if there's an endpoint available for getting available models
   - If we hardcode names in the codebase then we'll have to make changes to the code if OpenAI renames or add a new model (rarely)
- Or this can be a raw input where the user can enter the model name, but there's room for errors if there's a typo in the name then we'll need additional error handling

**Comment by imrishabh18** [comment]
Hey @abhagsain I would like to take this up.

**Comment by abhagsain** [comment]
Thanks @imrishabh18 let me know if you have any questions about the codebase. 
We don't have a contribution guide yet but running the project is pretty straightforward. Please visit the [Oclif docs](https://oclif.io/)

**Comment by chatmark** [comment]
Would that more dynamic if we could keep the original one as `ai ask` while the new one is `ai code` for example?

**Comment by abhagsain** [comment]
> Would that more dynamic if we could keep the original one as `ai ask` while the new one is `ai code` for example?

They both do the same thing so I'm not sure if we need a separate command for `code`. There might be some Pricing differences but we should let users switch b/w models if they are concerned about the pricing but cheaper models don't give good results. 

@imrishabh18 Please let me know if you're busy and can't pick this up. I'll assign it to myself. 

Also, I'm playing around with Fine Tuning a model only for the CLI so let's see if it reduces cost and improves responses so if you're someone who works extensively with CLI. Please fill out this [short form](https://tally.so/r/wLDXYl)

**Comment by imrishabh18** [comment]
Really sorry @abhagsain. I wanted to work on this one, but have a few things going on and can't find time to work on it. Please assign it to yourself. Will be around if something else comes up later, would be happy to check it out!

**Comment by abhagsain** [comment]
> Really sorry @abhagsain. I wanted to work on this one, but have a few things going on and can't find time to work on it. Please assign it to yourself. Will be around if something else comes up later, would be happy to check it out!

No problem

**Comment by abhagsain** [comment]
✅ done @taesiri Please install the latest version
```
npm install @abhagsain/ai-cli@latest -g
```
